name: Comentar en Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comentar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Comentar en el PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            CI/CD en acción. Ejecutando tareas …
